### ISSUE TITLE
Build error

### ISSUE THREAD

**Issue by IzzySoft** [bojko108/mobile-tile-server#12]
when I try building v5.0 from source, build fails with

```
java.lang.NoClassDefFoundError: Could not initialize class org.codehaus.groovy.vmplugin.v7.Java7
  at org.codehaus.groovy.vmplugin.VMPluginFactory.<clinit>(VMPluginFactory.java:43)
  at org.codehaus.groovy.reflection.GroovyClassValueFactory.<clinit>(GroovyClassValueFactory.java:35)
..

Caused by: java.lang.ExceptionInInitializerError: Exception org.codehaus.groovy.GroovyBugError [in thread "Daemon worker"]
  at org.codehaus.groovy.vmplugin.v7.Java7.<clinit>(Java7.java:45)
  at java.base/jdk.internal.reflect.NativeConstructorAccessorImpl.newInstance0(Native Method)
..

Could not initialize class org.codehaus.groovy.reflection.ReflectionCache
> Exception java.lang.NoClassDefFoundError: Could not initialize class org.codehaus.groovy.vmplugin.v7.Java7 [in thread "Daemon worker"]
```

I just run `./gradlew assembleRelease` with OpenJDK-17 on Debian bookworm. Any idea what I might be missing there?  Thanks in advance!

**Comment by IzzySoft** [comment]
@bojko108 any plans to work on this? Or did you already give up on the app?

**Comment by bojko108** [comment]
Hi, I'm not able to reproduce this build error. I've updated all dependencies, can you try the new version - #13 ?

I think the error you receive could be caused by old version of Gradle, try to update it.

**This is what I have for Gradle:
Android Gradle Plugin Version - 8.5.1
Gradle Version 8.7**

**Comment by IzzySoft** [comment]
Yes, thanks – that builds! Can you give me a ping once that PR is merged and a new release including these changes is available? For some background of my question:

At IzzyOnDroid we support [Reproducible Builds](https://reproducible-builds.org/) (see: [Reproducible Builds, special client support and more at IzzyOnDroid](https://android.izzysoft.de/articles/named/iod-rbs-mirrors-clients)). So I'm trying to establish such for your app. To do so, I'll need an APK you've build, and build one myself from the same commit to compare against (no worries, signing stuff is taken care for; at IoD we've currently almost 400 apps covered with RBs already).

So we'd appreciate if you could help making your build reproducible (if any more help is needed after the next release is there). We've also prepared some [hints on reproducible builds](https://gitlab.com/IzzyOnDroid/repo/-/wikis/Reproducible-Builds) for that.

Looking forward to your reply!

**Comment by bojko108** [comment]
Ok, I've created a new release - https://github.com/bojko108/mobile-tile-server/releases/tag/v5.1

I haven't used reproducible builds before, let me know if I need to make more changes.

**Comment by IzzySoft** [comment]
Oops… That one was built on Windows, so I had to amend the recipe (different line endings with `res/*.html`, `res/*.txt` and `META-INF/services/*`). No big deal, but you'd need to stick with one variant for release builds. I've now set it up to match your Windows builds; should you one day switch to build on Linux, the recipe needs to be adjusted back to its previous, simpler variant (without the adjustments for line endings).

Apart from that: I don't expect specific issues. The [hints on reproducible builds](https://gitlab.com/IzzyOnDroid/repo/-/wikis/Reproducible-Builds) I've linked you before should help you avoiding the most frequent "known culprits".

But for now, here comes your [welcome toot](https://floss.social/@IzzyOnDroid/113772527671950721) to raise attention to your efforts:

![image](https://github.com/user-attachments/assets/3801d5fd-3961-420d-92d3-faaec8dd7d7e)

Congrats! And if you have any questions, don't hesitate to ask :wink:

**Comment by bojko108** [comment]
Awesome, thank you! Sorry, I make many mistakes, because I'm not working with java frequently and do not make frequent releases - the app is simple, it does not provide rich functionality but gets the job done. I promise to be more careful in the future, as for the build system - no plans to switch on Linux for now.
